services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  server:
    container_name: server
    image: ${ECR_REGISTRY}/insight-server:latest
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  redis_data:
